Documentation:
  - changed-files:
      - any-glob-to-any-file: [ 'docs/**', 'README.md', 'MarketplaceDescription.md', 'CONTRIBUTING.md', 'CHANGELOG.md' ]

Actions:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**'

Dependencies:
  - head-branch: [ 'dependabot', 'bump' ]
  - changed-files:
      - any-glob-to-any-file: [ 'gradle/**', 'gradlew', 'gradlew.bat' ]

License:
  - changed-files:
      - any-glob-to-any-file: 'LICENSE'

Templates:
  - changed-files:
      - any-glob-to-any-file: [ '.github/ISSUE_TEMPLATE/**', '.github/pull_request_template.md', 'src/main/resources/fileTemplates/**' ]

Generated:
  - changed-files:
      - any-glob-to-any-file: 'src/main/gen/**'

Configuration:
  - changed-files:
      - any-glob-to-any-file: [ 'gradle.properties', 'build.gradle', '.gitignore', 'settings.gradle', '.github/labeler.yml', '.github/dependabot.yml' ]

Syntax:
  - changed-files:
      - any-glob-to-any-file: [ '**/*.bnf', '**/*.flex' ]

Test:
  - head-branch: [ '^test' ]
  - changed-files:
      - any-glob-to-any-file: 'src/test/**'

Enhancement:
  - head-branch: [ '^feat' ]

Change:
  - head-branch: [ '^change' ]

Patch:
  - head-branch: [ '^patch' ]

Chore:
  - head-branch: [ '^chore' ]