import org.jetbrains.changelog.Changelog
import org.jetbrains.changelog.ExtensionsKt
import org.jetbrains.intellij.platform.gradle.TestFrameworkType

plugins {
    id 'java'
    // versions specified in gradle/libs.versions.toml
    alias(libs.plugins.intelliJPlatform)
    alias(libs.plugins.changelog)
    alias(libs.plugins.grammarkit)
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    testImplementation libs.junit
    testImplementation libs.opentest4j

    intellijPlatform {
        // content pulled from gradle.properties

        def type = providers.gradleProperty('platformType')
        def version = providers.gradleProperty('platformVersion')
        create(type, version)

        def bundledPlatformPlugins = providers.gradleProperty('platformBundledPlugins').map { it.split(',').toList() }
        bundledPlugins(bundledPlatformPlugins)

        def platformPlugins = providers.gradleProperty('platformPlugins').map { it.split(',').toList() }
        plugins(platformPlugins)

        testFramework(TestFrameworkType.Platform.INSTANCE)
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

def projectRoot = 'dev/vala/jetbrains'
def projectSourcesRoot = layout.projectDirectory.dir('src/main/java').dir(projectRoot)
def generatedSourcesDir = layout.projectDirectory.dir('src/main/gen')
def pluginVersion = providers.gradleProperty('pluginVersion').get()

project.version = pluginVersion

// Parser/Lexer files generate to this src dir
sourceSets {
    main {
        java {
            srcDirs generatedSourcesDir
        }
    }
}

// https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform
intellijPlatform {

    // https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-pluginConfiguration
    pluginConfiguration {
        id = providers.gradleProperty('pluginId').get()
        name = providers.gradleProperty('pluginName').get()
        description = ExtensionsKt.markdownToHTML(file('MarketplaceDescription.md').text, '\n')

        project.changelog.version = pluginVersion

        changeNotes = project.changelog.renderItem(
            (project.changelog.getOrNull(pluginVersion) ?: project.changelog.getUnreleased())
                .withHeader(false)
                .withEmptySections(false),
            Changelog.OutputType.HTML)

        // https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-pluginConfiguration-ideaVersion
        ideaVersion {
            sinceBuild = providers.gradleProperty('pluginSinceBuild')
            untilBuild = providers.gradleProperty('pluginUntilBuild')
        }

        // https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-pluginConfiguration-vendor
        vendor {
            name = providers.gradleProperty('vendorName').get()
            email = providers.gradleProperty('vendorEmail').get()
            url = providers.gradleProperty('vendorUrl').get()
        }
    }

    // https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-signing
    signing {
        certificateChain = providers.environmentVariable('CERTIFICATE_CHAIN')
        privateKey = providers.environmentVariable('PRIVATE_KEY')
        password = providers.environmentVariable('PRIVATE_KEY_PASSWORD')
    }

    // https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-publishing
    publishing {
        token = providers.environmentVariable('PUBLISH_TOKEN')
        channels = ['default']
    }

    // https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-pluginVerification
    pluginVerification {
        ides {
            recommended()
        }
    }
}

// Configure Gradle Changelog Plugin - read more: https://github.com/JetBrains/gradle-changelog-plugin
changelog {
    groups.empty()
    repositoryUrl = providers.gradleProperty('pluginRepositoryUrl')
}

tasks {
    wrapper {
        gradleVersion = providers.gradleProperty('gradleVersion').get()
    }

    // https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-tasks.html#publishPlugin
    publishPlugin {
        dependsOn(patchChangelog)
    }

    // https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-tasks.html#generateLexer
    generateLexer {
        sourceFile = projectSourcesRoot.file('syntax/Vala.flex')
        targetRootOutputDir = generatedSourcesDir
        packageName = "${projectRoot.replace('/', '.')}.lexer"
        pathToClass = "${projectRoot}/lexer/ValaLexer.java"
        purgeOldFiles = true
    }

    // https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-tasks.html#generateParser
    generateParser {
        sourceFile = projectSourcesRoot.file('syntax/Vala.bnf')
        targetRootOutputDir = generatedSourcesDir
        pathToParser = "${projectRoot}/parser/ValaParser.java"
        pathToPsiRoot = "${projectRoot}/parser/psi"
        purgeOldFiles = true
    }
}

intellijPlatformTesting {
    runIde {
    }
}
